services:
  tg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: wenkfort/tg-bot:latest
    container_name: tg-bot
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
