name: Docker Image CI

on:
  push:
    branches:
      - main
      - github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the Docker image
      run: docker buildx build --platform linux/arm/v7 -t tg-bot-arm:latest --load .
    - name: Save the Docker image
      run: docker save tg-bot-arm:latest -o tg-bot-arm.tar.gz
    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: tg-bot-arm
        path: tg-bot-arm.tar.gz
